### ISSUE TITLE
sonar frames are inverted left-right

### ISSUE THREAD

**Issue by vrabaud** [ros-naoqi/nao_robot#15]
Just open up a tf in RViz and you'll see the problem.
@keulYSMB , didn't that happen before ?

**Comment by keulYSMB** [comment]
Yes and it has been fixed a few months ago.
I think some commits have been lost or history has been overwritten at some point because it's not the first time a previously fixed bug shows up.
Do you want me to fix it ?
Can you ask sbarthelemy to generate an URDF to see if the problem is in Aldebaran's library ?

**Comment by keulYSMB** [comment]
I have this issue with the binary package but not with the github version. Seems that the sonars are at the right place. 
@vrabaud Can you confirm ?

**Comment by keulYSMB** [comment]
I fixed it at the beginning of January indeed (while fixing the gazebo files). We just need another release.

**Comment by vrabaud** [comment]
So you fixed it for V40 but not for V50. I am still releasing but as you said, this has to be a bug in our internal library.
Still, releasing for now.

**Comment by vrabaud** [comment]
The error comes from here no ?
https://github.com/ros-naoqi/naoqi_bridge/blob/master/naoqi_tools/src/naoqi_tools/nao_dictionaries.py#L56

**Comment by keulYSMB** [comment]
Yes Definitely ! Stupid copy paste mistake :s
